package com.bc.exception;


import jakarta.ws.rs.core.MediaType;
import jakarta.ws.rs.core.Response;
import jakarta.ws.rs.ext.ExceptionMapper;
import jakarta.ws.rs.ext.Provider;

/**
 * Mapper class for mapping custom exception to ErrorResponse class object.
 */
@Provider
public class CommonExceptionMapper implements ExceptionMapper<CommonException> {

    /**
     * @param exception Custom exception generated by the various validations and error handling withing the service.
     * @return A response object mapped with custom error code, error message and http status code
     */
    @Override
    public Response toResponse(CommonException exception) {

        ErrorResponse errorResponse = new ErrorResponse();
        errorResponse.setErrorMessage(exception.getMessage());
        errorResponse.setErrorCode(exception.getErrorCode());
        errorResponse.setHttpStatusCode(exception.getHttpStatusCode());
        return Response
                .status(exception.getHttpStatusCode())
                .entity(errorResponse)
                .type(MediaType.APPLICATION_JSON_TYPE)
                .build();
    }
}