package com.bc.application.service.actions;

import com.bc.utilities.TripleDES;

/**
 * This class defines methods required for generating an IBM 3624 PIN based on an offset.
 */
public class GenerateIBM3624Pin {

    private String pan;
    private String pin;
    private String pinLength;
    private String naturalPin;
    private String pinOffset;

    /**
     * Private constructor to be used by the builder pattern method to instantiate the object and call methods.
     * @param builder
     */
    private GenerateIBM3624Pin(Builder builder) {

        this.pan = builder.pan;
        this.pin = builder.pin;
        this.pinLength = builder.pinLength;
        this.naturalPin = builder.naturalPin;
        this.pinOffset = builder.pinOffset;
    }

    @Override
    public String toString(){
        return this.getClass().getSimpleName() +
                " { " +
                "pan: " + pan + ", " +
                "pin: " + pin + ", " +
                "pinLength: " + pinLength + ", " +
                "naturalPin: " + naturalPin + ", " +
                "pinOffset: " + pinOffset +
                " }";
    }
    /**
     * Public builder method for initiating sequential builder methods for IBM 3624 PIN generation.
     * @return new Builder class instance.
     */
    public static GetPinValidationData builder(){
        return new Builder();
    }

    /**
     * Interface defining method for extracting Pin validation data from PAN.
     */
    public interface GetPinValidationData {
        /**
         * Generate PIN validation data from PAN, i.e., rightmost 12 digits from PAN excluding check digit.
         * @param pan PAN for which PIN must be generated.
         * @return 12 digit PIN validation data.
         */
        TdeaEncryptPinValidationData getPinValidationData (String pan);
    }

    /**
     * Interface defining method for TDEA encrypting the PIN validation data.
     */
    public interface TdeaEncryptPinValidationData {
        /**
         * Encrypt the PIN validation data using PIN Verification Key (PVK).
         * @param pinVerificationKey PIN Verification Key.
         * @return PVK encrypted PIN validation data.
         */
        DecimaliseEncryptedValidationData encryptPinValidationData (String pinVerificationKey);
    }

    /**
     * Interface defining methods for decimalisation of the encrypted PIN Validation Data and generating intermediate PIN.
     */
    public interface DecimaliseEncryptedValidationData {
        /**
         * Decimalise TDEA encrypted PIN Validation Data using an input decimalisation table.
         * @param decimalisationTable Decimalisation table to be used for decimalisation and data scrambling.
         * @return Intermediate PIN generated by transforming encrypted PIN validation data using decimalisation table.
         */
        TruncateToPinLength decimaliseEncryptedValidationData (String decimalisationTable);
    }

    /**
     * Interface defining methods for truncating the intermediate PIN to assigned PIN length.
     */
    public interface TruncateToPinLength {
        /**
         * Truncate intermediate PIN to assigned PIN length and generate natural PIN.
         * @param pinLength Assinged PIN length for the natural PIN.
         * @return Natural PIN generated.
         */
        AddPinOffset truncateToPinLength (int pinLength);
    }

    /**
     * Interface defining methods for performing PINOffset addition to natural PIN.
     */
    public interface AddPinOffset {
        /**
         * Module 10 add PIN Offset to the natural PIN, to generate PIN.
         * @param pinOffset Offset to be added to natural PIN.
         * @return Generated PIN.
         */
        GenerateResponse addPinOffset (String pinOffset);
    }

    /**
     *  Interface defining the final method in the builder sequence.
     */
    public interface GenerateResponse {
        /**
         * Method for building the response data.
         * @return Generated PIN.
         */
        GenerateIBM3624Pin build();
    }

    /**
     * Private class implementing the builder interfaces and defining the concrete methods to be used for IBM3624 PIN generation.
     */
    private static class Builder implements GetPinValidationData, TdeaEncryptPinValidationData, DecimaliseEncryptedValidationData, AddPinOffset, TruncateToPinLength, GenerateResponse {

        private String pan;
        private String pin;
        private String pinLength;
        private String pinOffset;
        private String pinValidationData;
        private String encryptedPinValidationData;
        private String intermediatePin;
        private String naturalPin;

        private static final String decimalisationTable = "0123456789012345";

        /**
         * Generate PIN validation data from PAN, i.e., rightmost 12 digits from PAN excluding check digit.
         *
         * @param pan PAN for which PIN must be generated.
         * @return 12 digit PIN validation data.
         */
        @Override
        public TdeaEncryptPinValidationData getPinValidationData(String pan) {
            final int VALIDATION_DATA_LENGTH = 12;
            // Calculate start index by subtracting validation data length + 1
            int startIndex = (pan.length() - VALIDATION_DATA_LENGTH) - 1;
            // Calculate end index by excluding check digit
            int endIndex = pan.length() - 1;
            this.pan = pan;
            this.pinValidationData = pan.substring(startIndex, endIndex);
            this.pinValidationData = this.pinValidationData + "F".repeat(16 - this.pinValidationData.length());
            return this;
        }

        /**
         * Encrypt the PIN validation data using PIN Verification Key (PVK).
         *
         * @param pinVerificationKey PIN Verification Key.
         * @return PVK encrypted PIN validation data.
         */
        @Override
        public DecimaliseEncryptedValidationData encryptPinValidationData(String pinVerificationKey) {
            encryptedPinValidationData = TripleDES.encrypt(pinValidationData, pinVerificationKey);
            return this;
        }

        /**
         * Decimalise TDEA encrypted PIN Validation Data using an input decimalisation table.
         *
         * @param decimalisationTable     Decimalisation table to be used for decimalisation and data scrambling.
         * @return Intermediate PIN generated by transforming encrypted PIN validation data using decimalisation table.
         */
        @Override
        public TruncateToPinLength decimaliseEncryptedValidationData(String decimalisationTable) {
            char [] encryptedValidationDataArray = encryptedPinValidationData.toCharArray();
            char [] decimalisationTableArray = decimalisationTable.toCharArray();
            StringBuilder decimalisedPinValidationData = new StringBuilder();
            for (char c : encryptedValidationDataArray) {
                decimalisedPinValidationData.append(decimalisationTableArray[Integer.parseInt(String.valueOf(c), 16)]);
            }
            intermediatePin = decimalisedPinValidationData.toString();
            return this;
        }

        /**
         * Truncate intermediate PIN to assigned PIN length and generate natural PIN.
         *
         * @param pinLength       Assigned PIN length for the natural PIN.
         * @return Natural PIN generated.
         */
        @Override
        public AddPinOffset truncateToPinLength (int pinLength) {
            this.pinLength = String.valueOf(pinLength);
            naturalPin = intermediatePin.substring(0, pinLength);
            return this;
        }

        /**
         * Module 10 add PIN Offset to the natural PIN, to generate PIN.
         *
         * @param pinOffset  Offset to be added to natural PIN.
         * @return Generated PIN.
         */
        @Override
        public GenerateResponse addPinOffset(String pinOffset) {
            StringBuilder offsetAdjustedPin = new StringBuilder();
            String adjustedPinOffset = pinOffset.substring(pinOffset.length() - Integer.parseInt(pinLength));
            for(int i = 0; i < adjustedPinOffset.length(); i++){
                int pinDigit = Integer.parseInt(String.valueOf(naturalPin.charAt(i)));
                int offsetDigit = Integer.parseInt(String.valueOf(adjustedPinOffset.charAt(i)));
                offsetAdjustedPin.append((pinDigit + offsetDigit) % 10);
            }
            this.pinOffset = pinOffset;
            this.pin = offsetAdjustedPin.toString();
            return this;
        }

        /**
         * Method for building the response data.
         * @return Generated PIN.
         */
        @Override
        public GenerateIBM3624Pin build() {
            return new GenerateIBM3624Pin(this);
        }
    }

}
